### ISSUE TITLE
Error when creating new UUID while adding user

### ISSUE THREAD

**Issue by pskura** [faisalthaheem/hurtrade#27]
When trying to add new user in the table, I get the following error:

"invalid input syntax for useruuid (...) character varying"

Is there any specific way to assign UUID?

**Comment by faisalthaheem** [comment]
Please use a tool such as following to generate a guid
https://www.uuidgenerator.net/

it must be of the following format
722128cb-c2ff-46c8-8822-6a616ac5b505
