### ISSUE TITLE
[Error] Login

### ISSUE THREAD

**Issue by dbof10** [faisalthaheem/hurtrade#28]
username | postgres
-- | --
password | faisal123

I can't login with this account. how to get or create a new ccount?

**Comment by SalmanSanjeet** [comment]
Facing Same Issue.
Please Help.

**Comment by faisalthaheem** [comment]
Are you trying to login to the db? can you please provide steps to reproduce?

**Comment by SalmanSanjeet** [comment]
[error doc.docx](https://github.com/faisalthaheem/hurtrade/files/5986879/error.doc.docx)

**Comment by SalmanSanjeet** [comment]
I followed step (mentioned in doc) and not able to login.
please Help

**Comment by faisalthaheem** [comment]
Thanks Salman, I'm looking into this.

**Comment by faisalthaheem** [comment]
Issue resolved, please refer to the updated wiki page
https://github.com/faisalthaheem/hurtrade/wiki/Creating-a-new-user

Kindly note the following addition/changes to the page

1. **The credentials to login to pgAdmin web interface are as follows**
2. **Use the following credentials to connect to the pgsql db**
